name: Wails build with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Compose up
      run: docker-compose up -d

    - name: Run Wails Build in Docker
      run: |
        docker exec move-cursor /bin/sh -c "wails build -n App"

    - name: Docker Compose down
      run: docker-compose down
